spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
leve:
  auth:
    client:
      id: admin
      secret: admin123456
      url: auth
#      url: localhost:8080
      tokenHead: Bearer
security:
  oauth2:
    resource:
      token-info-uri:
