spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  application:
    name: resource
eureka:
  instance:
    prefer-ip-address: true
  #    ip-address: ${EUREKA_CLIENT_IP}
  client:
    service-url:
      defaultZone: http://peer1:9000/eureka/
    enabled: true


leve:
  auth:
    client:
      id: admin
      secret: admin123456
      url: authentication
#      url: localhost:8080
      tokenHead: Bearer

